{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import json\n",
    "import random\n",
    "\n",
    "# DATABASE SYSTEM: Load existing data when the program starts\n",
    "try:\n",
    "    with open(\"bank_database.json\", \"r\", encoding=\"utf-8\") as file:\n",
    "        cards = json.load(file)\n",
    "except FileNotFoundError:\n",
    "    cards = {}\n",
    "\n",
    "# DATABASE SYSTEM: Function to save current data permanently to the storage\n",
    "def save_data():\n",
    "    with open(\"bank_database.json\", \"w\", encoding=\"utf-8\") as file:\n",
    "        json.dump(cards, file, ensure_ascii=False, indent=4)\n",
    "\n",
    "digits = [\"1\", \"2\", \"3\", \"4\", \"5\", \"6\", \"7\", \"8\", \"9\", \"0\"]\n",
    "\n",
    "def create_card():\n",
    "    while True:\n",
    "        print(\"\\nWelcome to the Card Creation System. Please type 'CONFIRM' to start the process.\")\n",
    "        confirmation = input(\"Type CONFIRM to start the process: \")\n",
    "        if confirmation == \"CONFIRM\":\n",
    "            pin = int(input(\"Please set a !numerical! PIN for your card: \"))\n",
    "            confirm_pin = int(input(\"Please confirm your PIN: \"))\n",
    "            if pin == confirm_pin:\n",
    "                print(\"Your PIN has been successfully created. Now, please enter your personal details.\")\n",
    "                iban = \"\".join(random.choices(digits, k=8))\n",
    "                id_number = int(input(\"Enter your ID Number (TC): \"))\n",
    "                cvv = \"\".join(random.choices(digits, k=3))\n",
    "                first_name = input(\"Enter your first name: \")\n",
    "                last_name = input(\"Enter your last name: \")\n",
    "                birth_date = input(\"Enter your birth date: \")\n",
    "                support_code = \"\".join(random.choices(digits, k=5))\n",
    "                \n",
    "                print(\"Your card has been successfully created!\")\n",
    "                print(f\"\"\"\n",
    "                ============================================================\n",
    "                |    VIRTUAL CARD VIEW (DO NOT SHARE FOR YOUR SECURITY)    |\n",
    "                ============================================================\n",
    "                |                                                          |\n",
    "                | NAME: {first_name}           IBAN: {iban}                |\n",
    "                | SURNAME: {last_name}        PIN: {pin}                  |\n",
    "                | ID NO: {id_number}          CVV: {cvv}                  |\n",
    "                | BIRTHDATE: {birth_date}     Balance: 0                  |\n",
    "                | Support Code: {support_code}  REPUBLIC OF TURKEY-K0938    |\n",
    "                =============================================================\"\"\")\n",
    "                \n",
    "                cards[iban] = {\n",
    "                    \"first_name\": first_name,\n",
    "                    \"last_name\": last_name,\n",
    "                    \"id_number\": id_number,\n",
    "                    \"birth_date\": birth_date,\n",
    "                    \"support_code\": support_code,\n",
    "                    \"iban\": iban,\n",
    "                    \"pin\": pin,\n",
    "                    \"cvv\": cvv,\n",
    "                    \"balance\": 0,\n",
    "                }\n",
    "                save_data() # Save the newly created card to the database file\n",
    "                break\n",
    "            else:\n",
    "                print(\"PINs do not match. Please enter it correctly.\")\n",
    "        else:\n",
    "            print(\"Since you typed something other than CONFIRM, the system is shutting down...\")\n",
    "            break\n",
    "\n",
    "# ATM SYSTEM HISTORY TRACKERS\n",
    "history_deposit = []\n",
    "history_withdraw = []\n",
    "history_transfer = []\n",
    "history_balance_check = 0\n",
    "history_pin_change = []\n",
    "history_support_call = 0\n",
    "history_logs_check = 0\n",
    "history_card_creation = 0\n",
    "history_card_info_check = 0\n",
    "\n",
    "while True:\n",
    "    print(\"\\nWelcome to Emir ATM. System is launching...🤖\\nPress 1 to Deposit Money\\nPress 2 to Withdraw Money\\nPress 3 to Transfer Money (Remittance)\\nPress 4 to Check Balance\\nPress 5 to Change PIN\\nPress 6 to Contact Customer Representative\\nPress 7 to Query Transaction History\\nPress 8 to Create a New Card\\nPress 9 to View Card Information\\nPress 0 to Exit System. Have a nice day :)\")\n",
    "    selected_option = int(input(\"Please enter a choice (0-9): \"))\n",
    "    \n",
    "    if selected_option < 0 or selected_option > 9:\n",
    "        print(\"Invalid choice. Please press one of the given numbers.\")\n",
    "        \n",
    "    elif selected_option == 1:\n",
    "        iban_input = input(\"Please enter your IBAN: \")\n",
    "        if iban_input in cards:\n",
    "            user_data = cards[iban_input]\n",
    "            amount = int(input(\"Enter the amount to deposit: \"))\n",
    "            user_data['balance'] += amount\n",
    "            save_data() # Save the updated balance to file\n",
    "            print(\"Transaction complete.\")\n",
    "            history_deposit.append(amount)\n",
    "        else:\n",
    "            print(\"No account found with this IBAN.\")\n",
    "            \n",
    "    elif selected_option == 2:\n",
    "        iban_input = input(\"Please enter your IBAN: \")\n",
    "        if iban_input in cards:\n",
    "            user_data = cards[iban_input]\n",
    "            amount = int(input(\"Enter the amount to withdraw: \"))\n",
    "            if amount > user_data['balance']:\n",
    "                print(\"The amount to withdraw cannot exceed your current balance.\")\n",
    "            else:\n",
    "                user_data['balance'] -= amount\n",
    "                save_data() # Save the updated balance to file\n",
    "                history_withdraw.append(amount)\n",
    "                print(\"Transaction successfully completed.\")\n",
    "        else:\n",
    "            print(\"No account found with this IBAN.\")\n",
    "            \n",
    "    elif selected_option == 3:\n",
    "        sender_iban = input(\"Enter your IBAN: \")\n",
    "        if sender_iban in cards:\n",
    "            sender_card = cards[sender_iban]\n",
    "            print(f\"\\nWelcome {sender_card['first_name']}, Current Balance: {sender_card['balance']}\")\n",
    "            receiver_iban = input(\"Enter the IBAN you want to transfer money to: \")\n",
    "            if receiver_iban in cards:\n",
    "                receiver_card = cards[receiver_iban]\n",
    "                if sender_card == receiver_card:\n",
    "                    print(\"You cannot transfer money to your own account.\")\n",
    "                else:\n",
    "                    transfer_amount = int(input(\"Enter the transfer amount: \"))\n",
    "                    if sender_card['balance'] >= transfer_amount:\n",
    "                        sender_card['balance'] -= transfer_amount\n",
    "                        receiver_card['balance'] += transfer_amount\n",
    "                        save_data() # Save both account updates to file\n",
    "                        print(f\"Transaction successful. {transfer_amount} has been successfully sent to {receiver_card['first_name']}.\")\n",
    "                        print(f\"Your remaining balance is {sender_card['balance']}.\")\n",
    "                        history_transfer.append(transfer_amount)\n",
    "                    else:\n",
    "                        print(\"Transfer amount cannot exceed your balance.\")\n",
    "            else:\n",
    "                print(\"No account found with the receiver's IBAN.\")\n",
    "        else:\n",
    "            print(\"No account found with your IBAN.\")\n",
    "            \n",
    "    elif selected_option == 4:\n",
    "        iban_input = input(\"Please enter your IBAN: \")\n",
    "        if iban_input in cards:\n",
    "            print(f\"\\nYour card balance is: {cards[iban_input]['balance']}\")\n",
    "            history_balance_check += 1\n",
    "        else:\n",
    "            print(\"No account found with this IBAN.\")\n",
    "            \n",
    "    elif selected_option == 5:\n",
    "        iban_input = input(\"Enter your IBAN: \")\n",
    "        if iban_input in cards:\n",
    "            user_data = cards[iban_input]\n",
    "            print(\"\\nLogin Successful!\")\n",
    "            current_pin = int(input(\"Please enter your current PIN: \"))\n",
    "            if current_pin == user_data['pin']:\n",
    "                new_pin = int(input(\"Enter your new PIN: \"))\n",
    "                \n",
    "                # Check if this PIN is already used by another card in the system\n",
    "                pin_exists = False\n",
    "                for card_id in cards:\n",
    "                    if cards[card_id]['pin'] == new_pin:\n",
    "                        pin_exists = True\n",
    "                        break\n",
    "                        \n",
    "                if pin_exists:\n",
    "                    print(\"This PIN is currently being used by another account in the system. Please choose another PIN.\")\n",
    "                else:\n",
    "                    user_data['pin'] = new_pin\n",
    "                    save_data() # Save the new PIN to file\n",
    "                    print(\"\\nYour PIN has been successfully changed.\")\n",
    "                    history_pin_change.append(new_pin)\n",
    "            else:\n",
    "                print(\"\\nYour current PIN was entered incorrectly.\")\n",
    "        else:\n",
    "            print(\"Your IBAN does not exist in our system.\")\n",
    "            \n",
    "    elif selected_option == 6:\n",
    "        iban_input = input(\"Please enter your IBAN: \")\n",
    "        if iban_input in cards:\n",
    "            user_data = cards[iban_input]\n",
    "            input_support_code = input(\"Enter your customer representative code: \")\n",
    "            if input_support_code == user_data['support_code']:\n",
    "                print(\"Connecting to your representative...\")\n",
    "                history_support_call += 1\n",
    "            else:\n",
    "                print(\"Representative code is incorrect.\")\n",
    "        else:\n",
    "            print(\"Please make sure you entered the correct IBAN.\")\n",
    "            \n",
    "    elif selected_option == 7:\n",
    "        history_logs_check += 1\n",
    "        print(\"\\nCompiling your transaction history so far ⚙️.\\nDeposit history:\", history_deposit, \"\\nWithdraw history:\", history_withdraw, \"\\nTransfer history:\", history_transfer, \"\\nBalance check count:\", history_balance_check, \"\\nPIN change history:\", history_pin_change, \"\\nSupport call count:\", history_support_call, \"\\nHistory query count:\", history_logs_check, \"\\nCard creation count:\", history_card_creation, \"\\nCard info check count:\", history_card_info_check, \"\\nThis data represents the session log of this ATM. Have a good day.\")\n",
    "        \n",
    "    elif selected_option == 8:\n",
    "        print(\"\\nStarting card creation process...\")\n",
    "        create_card()\n",
    "        history_card_creation += 1\n",
    "        \n",
    "    elif selected_option == 9:\n",
    "        iban_input = input(\"Please enter your IBAN: \")\n",
    "        if iban_input in cards:\n",
    "            user_data = cards[iban_input]\n",
    "            print(\"Compiling card details...\")\n",
    "            print(f\"\"\"\n",
    "            ===================================================================\n",
    "            |       VIRTUAL CARD VIEW (DO NOT SHARE FOR YOUR SECURITY)         |\n",
    "            ===================================================================\n",
    "            |                                                                 |\n",
    "            | NAME: {user_data['first_name']}         IBAN: {iban_input}                   |\n",
    "            | SURNAME: {user_data['last_name']}      PIN: {user_data['pin']}              |\n",
    "            | ID NO: {user_data['id_number']}         CVV: {user_data['cvv']}              |\n",
    "            | BIRTHDATE: {user_data['birth_date']}   Balance: {user_data['balance']}      |\n",
    "            | Support Code: {user_data['support_code']}   REPUBLIC OF TURKEY-K0938        |\n",
    "            ===================================================================\"\"\")\n",
    "            print(\"\\nCard information successfully displayed.\")\n",
    "            history_card_info_check += 1\n",
    "        else:\n",
    "            print(\"Your IBAN could not be found.\")\n",
    "            \n",
    "    elif selected_option == 0:\n",
    "        print(\"\\n\\nSYSTEM IS SHUTTING DOWN⚙️⚙️\")\n",
    "        break\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.1+"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
